// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// File: prisma.config.ts
import 'dotenv/config'; // 👈 This is the missing piece!
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: env('DATABASE_URL'), 
  },
});
